---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-<name to use>
  namespace: <namespace to use>
placementRef:
  name: placement-policy-<name-to-use>
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-<name to use>
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-<name to use>
  namespace: default
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: <key selector>, operator: In, values: ["<value of key>"]}
